server:
  port: 8081

test:
  property: test
  size: 24

spring:
  application:
    name: diary
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    dynamic: true
    listener:
        simple:
          auto-startup: true
  datasource:
    url: jdbc:postgresql://localhost:5445/diary-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

bot:
  name: "DiaryBot"
  token: {$BOT_TOKEN:}
