version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: diary-postgres
    ports:
      - "5445:5432"
    environment:
      POSTGRES_DB: diary-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: diary-rabbitmq
    ports:
      - "5672:5672"   # порт для приложений (AMQP)
      - "15672:15672" # веб-интерфейс управления
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  # MongoDB для Graylog
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    networks:
      - graylog

  # Elasticsearch для Graylog
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    networks:
      - graylog

  # Graylog
  graylog:
    image: graylog/graylog:5.2
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper123   # любой длинный случайный текст
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918  # это sha256("admin")
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    restart: unless-stopped
    networks:
      - graylog
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"   # веб-интерфейс Graylog
      - "12201:12201/udp" # GELF UDP для логов
      - "12201:12201/tcp" # GELF TCP
volumes:
  pgdata:
  rabbitmq_data:

networks:
  graylog:
    driver: bridge