version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: diary-postgres
    ports:
      - "5445:5432"
    environment:
      POSTGRES_DB: diary-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: